files:
  - source: /testing/**/*.json
    translation: /%original_path%/%two_letters_code%/test/%original_file_name%
  - source: /testing/**/*.po
    translation: /%original_path%/%two_letters_code%/%original_file_name%
