commit_message: HELLO
files:
  - source: /testing/samples/awesome/*.en.json
    translation: /%original_path%/%file_name%.%two_letters_code%.%file_extension%
    "translation_replace": {
      "en.": ""
     },
    "excluded_target_languages": [
      "uk",
      "fr"
    ]
