commit_message: HELLO
files:
  - source: /testing/samples/awesome/*.en.json
    translation: /%original_path%/%file_name%.%two_letters_code%.%file_extension%
    "excluded_target_languages": [
      "en"
    ],
    "translation_replace": {
      "en.": ""
     }
